require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Api::JobsController do

  # This should return the minimal set of attributes required to create a valid
  # Api::Job. As you add validations to Api::Job, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Api::JobsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all api_jobs as @api_jobs" do
      job = Api::Job.create! valid_attributes
      get :index, {}, valid_session
      assigns(:api_jobs).should eq([job])
    end
  end

  describe "GET show" do
    it "assigns the requested api_job as @api_job" do
      job = Api::Job.create! valid_attributes
      get :show, {:id => job.to_param}, valid_session
      assigns(:api_job).should eq(job)
    end
  end

  describe "GET new" do
    it "assigns a new api_job as @api_job" do
      get :new, {}, valid_session
      assigns(:api_job).should be_a_new(Api::Job)
    end
  end

  describe "GET edit" do
    it "assigns the requested api_job as @api_job" do
      job = Api::Job.create! valid_attributes
      get :edit, {:id => job.to_param}, valid_session
      assigns(:api_job).should eq(job)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Api::Job" do
        expect {
          post :create, {:api_job => valid_attributes}, valid_session
        }.to change(Api::Job, :count).by(1)
      end

      it "assigns a newly created api_job as @api_job" do
        post :create, {:api_job => valid_attributes}, valid_session
        assigns(:api_job).should be_a(Api::Job)
        assigns(:api_job).should be_persisted
      end

      it "redirects to the created api_job" do
        post :create, {:api_job => valid_attributes}, valid_session
        response.should redirect_to(Api::Job.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved api_job as @api_job" do
        # Trigger the behavior that occurs when invalid params are submitted
        Api::Job.any_instance.stub(:save).and_return(false)
        post :create, {:api_job => {  }}, valid_session
        assigns(:api_job).should be_a_new(Api::Job)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Api::Job.any_instance.stub(:save).and_return(false)
        post :create, {:api_job => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested api_job" do
        job = Api::Job.create! valid_attributes
        # Assuming there are no other api_jobs in the database, this
        # specifies that the Api::Job created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Api::Job.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => job.to_param, :api_job => { "these" => "params" }}, valid_session
      end

      it "assigns the requested api_job as @api_job" do
        job = Api::Job.create! valid_attributes
        put :update, {:id => job.to_param, :api_job => valid_attributes}, valid_session
        assigns(:api_job).should eq(job)
      end

      it "redirects to the api_job" do
        job = Api::Job.create! valid_attributes
        put :update, {:id => job.to_param, :api_job => valid_attributes}, valid_session
        response.should redirect_to(job)
      end
    end

    describe "with invalid params" do
      it "assigns the api_job as @api_job" do
        job = Api::Job.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Api::Job.any_instance.stub(:save).and_return(false)
        put :update, {:id => job.to_param, :api_job => {  }}, valid_session
        assigns(:api_job).should eq(job)
      end

      it "re-renders the 'edit' template" do
        job = Api::Job.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Api::Job.any_instance.stub(:save).and_return(false)
        put :update, {:id => job.to_param, :api_job => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested api_job" do
      job = Api::Job.create! valid_attributes
      expect {
        delete :destroy, {:id => job.to_param}, valid_session
      }.to change(Api::Job, :count).by(-1)
    end

    it "redirects to the api_jobs list" do
      job = Api::Job.create! valid_attributes
      delete :destroy, {:id => job.to_param}, valid_session
      response.should redirect_to(api_jobs_url)
    end
  end

end
