web:
    image: shaneburkhart/plansource:dev
    ports:
        - "3000:3000"
    links:
        - pg
    volumes:
        - ../../app:/app/app
        - ../../db:/app/db
        - ../../config/routes.rb:/app/config/routes.rb
    env_file:
        - ../../user.env

pg:
    image: postgres
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=mydb
    volumes:
        - ../../data/pg:/var/lib/postgresql/data
